# Generated by Django 5.0.1 on 2024-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='телеграм'),
        ),
    ]
