# Generated by Django 5.0.1 on 2024-01-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время')),
                ('action', models.CharField(max_length=500, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(verbose_name='приятная')),
                ('periodity', models.IntegerField(default=1, verbose_name='повторяем через')),
                ('reward', models.CharField(max_length=500, verbose_name='награждение')),
                ('duration', models.IntegerField(default=60, verbose_name='продолжительность в секундах')),
                ('is_public', models.BooleanField(verbose_name='можно опубликовать')),
                ('connected_habit', models.ForeignKey(null=True,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      to='habits.habit', verbose_name='связана с')),
            ],
        ),
    ]
