# Generated by Django 5.0.1 on 2024-01-07 23:45

import django.db.models.deletion
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_connected_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='connected_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', validators=[habits.validators.connected_is_pleasant], verbose_name='связана с'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=60, validators=[habits.validators.is_under120], verbose_name='продолжительность в секундах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='приятная'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodity',
            field=models.IntegerField(default=1, validators=[habits.validators.is_under7], verbose_name='повторяем через'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='награждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
    ]
