# Generated by Django 5.0.1 on 2024-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_connected_habit_alter_habit_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_send', models.DateField(verbose_name='дата последней отправки')),
            ],
        ),
    ]
