# Generated by Django 5.0.1 on 2024-01-19 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_sendinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendinglog',
            name='habit_sent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='привычка'),
            preserve_default=False,
        ),
    ]
